services:

  db:
    container_name: vicidial-db
    build:
      context: './docker/mysql'
      dockerfile: 'Dockerfile.mariadb'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-S", "/tmp/mysql.sock"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 20s

    env_file:
      - './docker/mysql/mysql.env'
    networks:
      backend:
        ipv4_address: 10.10.10.10

    # ports:
    #   - "127.0.0.1:3306:3306"

    # network_mode: host
    volumes:
      - db_data:/var/lib/mysql
      - db_log:/var/log/mysql
      - ./docker/mysql/import:/var/lib/mysql-files
      
  dialer:

    container_name: vicidial-dialer
    build:
      context: './docker/app'
      args:
        - VICI_DB=10.10.10.10
        - VICI_HOST=10.10.10.15
      dockerfile: 'Dockerfile.ubuntu'

    restart: unless-stopped
    depends_on:
      db:
        condition: 'service_healthy'
      # certbot:
      #   condition: 'service_completed_successfully'
    
    volumes:
      - /var/www/html
      - ./docker/certbot/letsencrypt/certs:/etc/letsencrypt
      - ./docker/certbot/letsencrypt/data:/var/lib/letsencrypt

    networks:
      backend:
        ipv4_address: 10.10.10.15
      frontend:


    ports:
      - "8080:80"
      - "5060:5060"
      - "4569:4569"

    # use to bind host to all ports
    # network_mode: host

    # comment the following line in production, it allows to have nice human-readable logs in dev
    # tty: true

  # certbot:
  #   image: certbot/certbot
  #   volumes_from:
  #     - app

  #   # set the domain & email for certbot here
  #   command: certonly --keep-until-expiring --standalone --email test@test.com --agree-tos --no-eff-email -d vici-dev.protect247.app

  #   # set proper network_mode to bind port 80 and get certificate before webserver starts
  #   network_mode: host

networks:
  backend:
    name: vici-backend
    driver: bridge
    internal: true
    # Set internal subnet
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24

  frontend:
    name: vici-frontend
    driver: bridge
 
# Volumes needed for mariadb persistency
volumes:
  db_data:
  db_log:
