use asterisk;

-- Insert records to asterisk.vicidial_country_iso_tld
INSERT IGNORE INTO `vicidial_country_iso_tld`(country_name, iso2, iso3, num3, tld)
VALUES 
    ('Afghanistan','AF','AFG','004','af'),
    ('Aland Islands','AX','ALA','248','ax'),
    ('Albania','AL','ALB','008','al'),
    ('Algeria','DZ','DZA','012','dz'),
    ('American Samoa','AS','ASM','016','as'),
    ('Andorra','AD','AND','020','ad'),
    ('Angola','AO','AGO','024','ao'),
    ('Anguilla','AI','AIA','660','ai'),
    ('Antarctica','AQ','ATA','010','aq'),
    ('Antigua and Barbuda','AG','ATG','028','ag'),
    ('Argentina','AR','ARG','032','ar'),
    ('Armenia','AM','ARM','051','am'),
    ('Aruba','AW','ABW','533','aw'),
    ('Australia','AU','AUS','036','au'),
    ('Austria','AT','AUT','040','at'),
    ('Azerbaijan','AZ','AZE','031','az'),
    ('Bahamas','BS','BHS','044','bs'),
    ('Bahrain','BH','BHR','048','bh'),
    ('Bangladesh','BD','BGD','050','bd'),
    ('Barbados','BB','BRB','052','bb'),
    ('Belarus','BY','BLR','112','by'),
    ('Belgium','BE','BEL','056','be'),
    ('Belize','BZ','BLZ','084','bz'),
    ('Benin','BJ','BEN','204','bj'),
    ('Bermuda','BM','BMU','060','bm'),
    ('Bhutan','BT','BTN','064','bt'),
    ('Bolivia (Plurinational State of)','BO','BOL','068','bo'),
    ('Bonaire, Sint Eustatius and Saba','BQ','BES','535','bq'),
    ('Bosnia and Herzegovina','BA','BIH','070','ba'),
    ('Botswana','BW','BWA','072','bw'),
    ('Bouvet Island','BV','BVT','074','bv'),
    ('Brazil','BR','BRA','076','br'),
    ('British Indian Ocean Territory','IO','IOT','086','io'),
    ('Brunei Darussalam','BN','BRN','096','bn'),
    ('Bulgaria','BG','BGR','100','bg'),
    ('Burkina Faso','BF','BFA','854','bf'),
    ('Burundi','BI','BDI','108','bi'),
    ('Cambodia','KH','KHM','116','kh'),
    ('Cameroon','CM','CMR','120','cm'),
    ('Canada','CA','CAN','124','ca'),
    ('Cabo Verde','CV','CPV','132','cv'),
    ('Cayman Islands','KY','CYM','136','ky'),
    ('Central African Republic','CF','CAF','140','cf'),
    ('Chad','TD','TCD','148','td'),
    ('Chile','CL','CHL','152','cl'),
    ('China','CN','CHN','156','cn'),
    ('Christmas Island','CX','CXR','162','cx'),
    ('Cocos (Keeling) Islands','CC','CCK','166','cc'),
    ('Colombia','CO','COL','170','co'),
    ('Comoros','KM','COM','174','km'),
    ('Congo','CG','COG','178','cg'),
    ('Congo (Democratic Republic of the)','CD','COD','180','cd'),
    ('Cook Islands','CK','COK','184','ck'),
    ('Costa Rica','CR','CRI','188','cr'),
    ('Cote d\'Ivoire','CI','CIV','384','ci'),
    ('Croatia','HR','HRV','191','hr'),
    ('Cuba','CU','CUB','192','cu'),
    ('CuraÃ§ao','CW','CUW','531','cw'),
    ('Cyprus','CY','CYP','196','cy'),
    ('Czech Republic','CZ','CZE','203','cz'),
    ('Denmark','DK','DNK','208','dk'),
    ('Djibouti','DJ','DJI','262','dj'),
    ('Dominica','DM','DMA','212','dm'),
    ('Dominican Republic','DO','DOM','214','do'),
    ('Ecuador','EC','ECU','218','ec'),
    ('Egypt','EG','EGY','818','eg'),
    ('El Salvador','SV','SLV','222','sv'),
    ('Equatorial Guinea','GQ','GNQ','226','gq'),
    ('Eritrea','ER','ERI','232','er'),
    ('Estonia','EE','EST','233','ee'),
    ('Ethiopia','ET','ETH','231','et'),
    ('Falkland Islands (Malvinas)','FK','FLK','238','fk'),
    ('Faroe Islands','FO','FRO','234','fo'),
    ('Fiji','FJ','FJI','242','fj'),
    ('Finland','FI','FIN','246','fi'),
    ('France','FR','FRA','250','fr'),
    ('French Guiana','GF','GUF','254','gf'),
    ('French Polynesia','PF','PYF','258','pf'),
    ('French Southern Territories','TF','ATF','260','tf'),
    ('Gabon','GA','GAB','266','ga'),
    ('Gambia','GM','GMB','270','gm'),
    ('Georgia','GE','GEO','268','ge'),
    ('Germany','DE','DEU','276','de'),
    ('Ghana','GH','GHA','288','gh'),
    ('Gibraltar','GI','GIB','292','gi'),
    ('Greece','GR','GRC','300','gr'),
    ('Greenland','GL','GRL','304','gl'),
    ('Grenada','GD','GRD','308','gd'),
    ('Guadeloupe','GP','GLP','312','gp'),
    ('Guam','GU','GUM','316','gu'),
    ('Guatemala','GT','GTM','320','gt'),
    ('Guernsey','GG','GGY','831','gg'),
    ('Guinea','GN','GIN','324','gn'),
    ('Guinea-Bissau','GW','GNB','624','gw'),
    ('Guyana','GY','GUY','328','gy'),
    ('Haiti','HT','HTI','332','ht'),
    ('Heard Island and McDonald Islands','HM','HMD','334','hm'),
    ('Vatican City','VA','VAT','336','va'),
    ('Honduras','HN','HND','340','hn'),
    ('Hong Kong','HK','HKG','344','hk'),
    ('Hungary','HU','HUN','348','hu'),
    ('Iceland','IS','ISL','352','is'),
    ('India','IN','IND','356','in'),
    ('Indonesia','ID','IDN','360','id'),
    ('Iran (Islamic Republic of)','IR','IRN','364','ir'),
    ('Iraq','IQ','IRQ','368','iq'),
    ('Ireland','IE','IRL','372','ie'),
    ('Isle of Man','IM','IMN','833','im'),
    ('Israel','IL','ISR','376','il'),
    ('Italy','IT','ITA','380','it'),
    ('Jamaica','JM','JAM','388','jm'),
    ('Japan','JP','JPN','392','jp'),
    ('Jersey','JE','JEY','832','je'),
    ('Jordan','JO','JOR','400','jo'),
    ('Kazakhstan','KZ','KAZ','398','kz'),
    ('Kenya','KE','KEN','404','ke'),
    ('Kiribati','KI','KIR','296','ki'),
    ('Korea (Democratic People\'s Republic of)','KP','PRK','408','kp'),
    ('Korea (Republic of)','KR','KOR','410','kr'),
    ('Kosovo','XK','XKX','?','?'),
    ('Kuwait','KW','KWT','414','kw'),
    ('Kyrgyzstan','KG','KGZ','417','kg'),
    ('Lao People\'s Democratic Republic','LA','LAO','418','la'),
    ('Latvia','LV','LVA','428','lv'),
    ('Lebanon','LB','LBN','422','lb'),
    ('Lesotho','LS','LSO','426','ls'),
    ('Liberia','LR','LBR','430','lr'),
    ('Libya','LY','LBY','434','ly'),
    ('Liechtenstein','LI','LIE','438','li'),
    ('Lithuania','LT','LTU','440','lt'),
    ('Luxembourg','LU','LUX','442','lu'),
    ('Macao','MO','MAC','446','mo'),
    ('Macedonia (the former Yugoslav Republic of)','MK','MKD','807','mk'),
    ('Madagascar','MG','MDG','450','mg'),
    ('Malawi','MW','MWI','454','mw'),
    ('Malaysia','MY','MYS','458','my'),
    ('Maldives','MV','MDV','462','mv'),
    ('Mali','ML','MLI','466','ml'),
    ('Malta','MT','MLT','470','mt'),
    ('Marshall Islands','MH','MHL','584','mh'),
    ('Martinique','MQ','MTQ','474','mq'),
    ('Mauritania','MR','MRT','478','mr'),
    ('Mauritius','MU','MUS','480','mu'),
    ('Mayotte','YT','MYT','175','yt'),
    ('Mexico','MX','MEX','484','mx'),
    ('Micronesia (Federated States of)','FM','FSM','583','fm'),
    ('Moldova (Republic of)','MD','MDA','498','md'),
    ('Monaco','MC','MCO','492','mc'),
    ('Mongolia','MN','MNG','496','mn'),
    ('Montenegro','ME','MNE','499','me'),
    ('Montserrat','MS','MSR','500','ms'),
    ('Morocco','MA','MAR','504','ma'),
    ('Mozambique','MZ','MOZ','508','mz'),
    ('Myanmar','MM','MMR','104','mm'),
    ('Namibia','NA','NAM','516','na'),
    ('Nauru','NR','NRU','520','nr'),
    ('Nepal','NP','NPL','524','np'),
    ('Netherlands','NL','NLD','528','nl'),
    ('New Caledonia','NC','NCL','540','nc'),
    ('New Zealand','NZ','NZL','554','nz'),
    ('Nicaragua','NI','NIC','558','ni'),
    ('Niger','NE','NER','562','ne'),
    ('Nigeria','NG','NGA','566','ng'),
    ('Niue','NU','NIU','570','nu'),
    ('Norfolk Island','NF','NFK','574','nf'),
    ('Northern Mariana Islands','MP','MNP','580','mp'),
    ('Norway','NO','NOR','578','no'),
    ('Oman','OM','OMN','512','om'),
    ('Pakistan','PK','PAK','586','pk'),
    ('Palau','PW','PLW','585','pw'),
    ('Palestine','PS','PSE','275','ps'),
    ('Panama','PA','PAN','591','pa'),
    ('Papua New Guinea','PG','PNG','598','pg'),
    ('Paraguay','PY','PRY','600','py'),
    ('Peru','PE','PER','604','pe'),
    ('Philippines','PH','PHL','608','ph'),
    ('Pitcairn','PN','PCN','612','pn'),
    ('Poland','PL','POL','616','pl'),
    ('Portugal','PT','PRT','620','pt'),
    ('Puerto Rico','PR','PRI','630','pr'),
    ('Qatar','QA','QAT','634','qa'),
    ('RÃ©union','RE','REU','638','re'),
    ('Romania','RO','ROU','642','ro'),
    ('Russian Federation','RU','RUS','643','ru'),
    ('Rwanda','RW','RWA','646','rw'),
    ('Saint Bartholemy','BL','BLM','652','gp'),
    ('Saint Helena, Ascension and Tristan da Cunha','SH','SHN','654','sh'),
    ('Saint Kitts and Nevis','KN','KNA','659','kn'),
    ('Saint Lucia','LC','LCA','662','lc'),
    ('Saint Martin (French part)','MF','MAF','663','gp'),
    ('Saint Pierre and Miquelon','PM','SPM','666','pm'),
    ('Saint Vincent and the Grenadines','VC','VCT','670','vc'),
    ('Samoa','WS','WSM','882','ws'),
    ('San Marino','SM','SMR','674','sm'),
    ('Sao Tome and Principe','ST','STP','678','st'),
    ('Saudi Arabia','SA','SAU','682','sa'),
    ('Senegal','SN','SEN','686','sn'),
    ('Serbia','RS','SRB','688','rs'),
    ('Seychelles','SC','SYC','690','sc'),
    ('Sierra Leone','SL','SLE','694','sl'),
    ('Singapore','SG','SGP','702','sg'),
    ('Sint Maarten (Dutch part)','SX','SXM','534','sx'),
    ('Slovakia','SK','SVK','703','sk'),
    ('Slovenia','SI','SVN','705','si'),
    ('Solomon Islands','SB','SLB','090','sb'),
    ('Somalia','SO','SOM','706','so'),
    ('South Africa','ZA','ZAF','710','za'),
    ('South Georgia and the South Sandwich Islands','GS','SGS','239','gs'),
    ('South Sudan','SS','SSD','728','ss'),
    ('Spain','ES','ESP','724','es'),
    ('Sri Lanka','LK','LKA','144','lk'),
    ('Sudan','SD','SDN','729','sd'),
    ('Suriname','SR','SUR','740','sr'),
    ('Svalbard and Jan Mayen','SJ','SJM','744','sj'),
    ('Swaziland','SZ','SWZ','748','sz'),
    ('Sweden','SE','SWE','752','se'),
    ('Switzerland','CH','CHE','756','ch'),
    ('Syrian Arab Republic','SY','SYR','760','sy'),
    ('Taiwan, Province of China','TW','TWN','158','tw'),
    ('Tajikistan','TJ','TJK','762','tj'),
    ('Tanzania, United Republic of','TZ','TZA','834','tz'),
    ('Thailand','TH','THA','764','th'),
    ('Timor-Leste','TL','TLS','626','tl'),
    ('Togo','TG','TGO','768','tg'),
    ('Tokelau','TK','TKL','772','tk'),
    ('Tonga','TO','TON','776','to'),
    ('Trinidad and Tobago','TT','TTO','780','tt'),
    ('Tunisia','TN','TUN','788','tn'),
    ('Turkey','TR','TUR','792','tr'),
    ('Turkmenistan','TM','TKM','795','tm'),
    ('Turks and Caicos Islands','TC','TCA','796','tc'),
    ('Tuvalu','TV','TUV','798','tv'),
    ('Uganda','UG','UGA','800','ug'),
    ('Ukraine','UA','UKR','804','ua'),
    ('United Arab Emirates','AE','ARE','784','ae'),
    ('United Kingdom of Great Britain and Northern Ireland','GB','GBR','826','uk'),
    ('United States of America','US','USA','840','us'),
    ('United States Minor Outlying Islands','UM','UMI','581','us'),
    ('Uruguay','UY','URY','858','uy'),
    ('Uzbekistan','UZ','UZB','860','uz'),
    ('Vanuatu','VU','VUT','548','vu'),
    ('Venezuela (Bolivarian Republic of)','VE','VEN','862','ve'),
    ('Viet Nam','VN','VNM','704','vn'),
    ('Virgin Islands (British)','VG','VGB','092','vg'),
    ('Virgin Islands (U.S.)','VI','VIR','850','vi'),
    ('Wallis and Futuna','WF','WLF','876','wf'),
    ('Western Sahara','EH','ESH','732','eh'),
    ('Yemen','YE','YEM','887','ye'),
    ('Zambia','ZM','ZMB','894','zm'),
    ('Zimbabwe','ZW','ZWE','716','zw');



-- Vicidial Statuses
INSERT IGNORE INTO `vicidial_statuses` 
(status, status_name, selectable, human_answered, category, sale, dnc, customer_contact, not_interested, unworkable, scheduled_callback, completed, min_sec, max_sec, answering_machine, modify_stamp)
VALUES 
    ('NEW','New Lead','N','N','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('QUEUE','Lead To Be Called','N','N','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('INCALL','Lead Being Called','N','N','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('DROP','Agent Not Available','N','Y','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('XDROP','Agent Not Available IN','N','Y','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('NA','No Answer AutoDial','N','N','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('CALLBK','Call Back','Y','Y','UNDEFINED','N','N','Y','N','N','Y','N',0,0,'N','2025-06-23 16:43:10'),
    ('CBHOLD','Call Back Hold','N','Y','UNDEFINED','N','N','Y','N','N','Y','N',0,0,'N','2025-06-23 16:43:10'),
    ('A','Answering Machine','Y','N','UNDEFINED','N','N','N','N','N','N','N',0,0,'Y','2025-06-23 16:43:10'),
    ('AA','Answering Machine Auto','N','N','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('AM','Answering Machine SentToMesg','N','N','UNDEFINED','N','N','N','N','N','N','N',0,0,'Y','2025-06-23 16:43:10'),
    ('AL','Answering Machine Msg Played','N','N','UNDEFINED','N','N','N','N','N','N','N',0,0,'Y','2025-06-23 16:43:10'),
    ('AFAX','Fax Machine Auto','N','N','UNDEFINED','N','N','N','N','Y','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('AB','Busy Auto','N','N','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('B','Busy','Y','N','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('DC','Disconnected Number','Y','N','UNDEFINED','N','N','N','N','Y','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('ADC','Disconnected Number Auto','N','N','UNDEFINED','N','N','N','N','Y','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('DEC','Declined Sale','Y','Y','UNDEFINED','N','N','Y','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('DNC','DO NOT CALL','Y','Y','UNDEFINED','N','Y','N','N','N','N','Y',0,0,'N','2025-06-23 16:43:10'),
    ('DNCL','DO NOT CALL Hopper Sys Match','N','N','UNDEFINED','N','Y','N','N','N','N','Y',0,0,'N','2025-06-23 16:43:10'),
    ('DNCC','DO NOT CALL Hopper Camp Match','N','N','UNDEFINED','N','Y','N','N','N','N','Y',0,0,'N','2025-06-23 16:43:10'),
    ('SALE','Sale Made','Y','Y','UNDEFINED','Y','N','N','N','N','N','Y',0,0,'N','2025-06-23 16:43:10'),
    ('N','No Answer','Y','N','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('NI','Not Interested','Y','Y','UNDEFINED','N','N','Y','Y','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('NP','No Pitch No Price','Y','Y','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('PU','Call Picked Up','N','N','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('PM','Played Message','N','N','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('XFER','Call Transferred','Y','Y','UNDEFINED','N','N','Y','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('ERI','Agent Error','N','N','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('SVYEXT','Survey sent to Extension','N','N','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('SVYVM','Survey sent to Voicemail','N','N','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('SVYHU','Survey Hungup','N','N','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('SVYREC','Survey sent to Record','N','N','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('QVMAIL','Queue Abandon Voicemail Left','N','N','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('RQXFER','Re-Queue','N','Y','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('TIMEOT','Inbound Queue Timeout Drop','N','Y','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('AFTHRS','Inbound After Hours Drop','N','Y','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('NANQUE','Inbound No Agent No Queue Drop','N','Y','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('IQNANQ','InQueue No-Agent-No-Queue drop','N','Y','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('PDROP','Outbound Pre-Routing Drop','N','Y','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('IVRXFR','Outbound drop to Call Menu','N','Y','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('SVYCLM','Survey sent to Call Menu','N','Y','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('MLINAT','Multi-Lead auto-alt set inactv','N','Y','UNDEFINED','N','N','N','N','N','N','Y',0,0,'N','2025-06-23 16:43:10'),
    ('MAXCAL','Inbound Max Calls Drop','N','Y','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('LRERR','Outbound Local Channel Res Err','N','Y','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('QCFAIL','QC_FAIL_CALLBK','N','Y','QC','N','N','Y','N','N','Y','N',0,0,'N','2025-06-23 16:43:10'),
    ('ADCT','Disconnected Number Temporary','N','N','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('LSMERG','Agent lead search old lead mrg','N','N','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('DAIR','Dead Air','Y','N','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10'),
    ('ADAIR','Dead Air Auto','N','N','UNDEFINED','N','N','N','N','N','N','N',0,0,'N','2025-06-23 16:43:10');



-- Vicidial settings containers
INSERT IGNORE INTO `vicidial_settings_containers` 
(container_id, container_notes, container_type, user_group, container_entry, modify_stamp)
VALUES 
    ('AGENT_CALLBACK_EMAIL ','Scheduled callback email alert settings','OTHER','---ALL---','; sending email address\r\nemail_from => vicidial@local.server\r\n\r\n; subject of the email\r\nemail_subject => Scheduled callback alert for --A--agent_name--B--\r\n\r\nemail_body_begin => \r\nThis is a reminder that you have a scheduled callback right now for the following lead:\r\n\r\nName: --A--first_name--B-- --A--last_name--B--\r\nPhone: --A--phone_number--B--\r\nAlt. phone: --A--alt_phone--B--\r\nEmail: --A--email--B--\r\nCB Comments: --A--callback_comments--B--\r\nLead Comments: --A--comments--B--\r\n\r\nPlease don\'t respond to this, fool.\r\n\r\nemail_body_end','2025-06-23 16:43:10'),
    ('TIMEZONES_USA','USA Timezone List','TIMEZONE_LIST','---ALL---','USA,AST,N,Atlantic Time Zone\nUSA,EST,Y,Eastern Time Zone\nUSA,CST,Y,Central Time Zone\nUSA,MST,Y,Mountain Time Zone\nUSA,MST,N,Arizona Time Zone\nUSA,PST,Y,Pacific Time Zone\nUSA,AKST,Y,Alaska Time Zone\nUSA,HST,N,Hawaii Time Zone\n','2025-06-23 16:43:10'),
    ('TIMEZONES_CANADA','Canadian Timezone List','TIMEZONE_LIST','---ALL---','CAN,NST,Y,Newfoundland Time Zone\nCAN,AST,Y,Atlantic Time Zone\nCAN,EST,Y,Eastern Time Zone\nCAN,CST,Y,Central Time Zone\nCAN,CST,N,Saskatchewan Time Zone\nCAN,MST,Y,Mountain Time Zone\nCAN,MST,N,Yukon Time Zone\nCAN,PST,Y,Pacific Time Zone\n','2025-06-23 16:43:10'),
    ('TIMEZONES_AUSTRALIA','Australian Timezone List','TIMEZONE_LIST','---ALL---','AUS,AEST,Y,Eastern Australia Time Zone\nAUS,AEST,N,Queensland Time Zone\nAUS,ACST,Y,Central Australia Time Zone\nAUS,ACST,N,Northern Territory Time Zone\nAUS,AWST,N,Western Australia Time Zone\n','2025-06-23 16:43:10'),
    ('PHONE_DEFAULTS','Default phone settings for preloading','PHONE_DEFAULTS','---ALL---','# Below are all phone settings recognized under the PHONE_DEFAULTS \r\n# container type and the type of data each accepts.  Any setting that\r\n# uses a default value in the database has said value pre-set below\r\n\r\n# 10 char max\r\nvoicemail_id => \r\n \r\n# 15 char max\r\nserver_ip => \r\n\r\n# 100 char max\r\npass => \r\n\r\n# 10 char max\r\nstatus => \r\n\r\n# Y/N only\r\nactive => Y\r\n\r\n# 50 char max\r\nphone_type => \r\n\r\n# \'SIP\',\'Zap\',\'IAX2\' or \'EXTERNAL\'\r\nprotocol => SIP\r\n\r\n# positive or negatier 2-decimal floating point number\r\nlocal_gmt => -5.00\r\n\r\n# 20 char max\r\nvoicemail_dump_exten => 85026666666666\r\n\r\n# 20 char max\r\noutbound_cid => \r\n\r\n# 100 char max\r\nemail => \r\n\r\n# 15 char max\r\ntemplate_id => \r\n\r\n# text, conf_override can span multiple lines, see below\r\nconf_override => \r\n# type=friend\r\n# host=dynamic\r\n# canreinvite=no\r\n# context=default1\r\n\r\n# 50 char max\r\nphone_context => default\r\n\r\n# Unsigned - max value 65536\r\nphone_ring_timeout => 60\r\n\r\n# 20 char max\r\nconf_secret => test\r\n\r\n# Y/N only\r\ndelete_vm_after_email => N\r\n\r\n# Options - Y, N, or Y_API_LAUNCH\r\nis_webphone => N\r\n\r\n# Y/N only\r\nuse_external_server_ip => N\r\n\r\n# 100 char max\r\ncodecs_list => \r\n\r\n# 0/1 only\r\ncodecs_with_template => 0\r\n\r\n# Options - Y, N, TOGGLE, or TOGGLE_OFF\r\nwebphone_dialpad => Y\r\n\r\n# Y/N only\r\non_hook_agent => N\r\n\r\n# Y/N only\r\nwebphone_auto_answer => Y\r\n\r\n# 30 char max\r\nvoicemail_timezone => eastern\r\n\r\n# 255 char max\r\nvoicemail_options => \r\n\r\n# 20 char max\r\nuser_group => ---ALL---\r\n\r\n# 100 char max\r\nvoicemail_greeting => \r\n\r\n# 20 char max\r\nvoicemail_dump_exten_no_inst => 85026666666667\r\n\r\n# Y/N only\r\nvoicemail_instructions => Y\r\n\r\n# Y/N only\r\non_login_report => N\r\n\r\n# 40 char max\r\nunavail_dialplan_fwd_exten => \r\n\r\n# 100 char max\r\nunavail_dialplan_fwd_context => \r\n\r\n# text\r\nnva_call_url => \r\n\r\n# 40 char max\r\nnva_search_method => \r\n\r\n# 255 char max\r\nnva_error_filename => \r\n\r\n# Integer, any size\r\nnva_new_list_id => 995\r\n\r\n# 10 char max\r\nnva_new_phone_code => 1\r\n\r\n# 6 char max\r\nnva_new_status => NVAINS\r\n\r\n# Y/N only\r\nwebphone_dialbox => Y\r\n\r\n# Y/N only\r\nwebphone_mute => Y\r\n\r\n# Y/N only\r\nwebphone_volume => Y\r\n\r\n# Y/N only\r\nwebphone_debug => N\r\n\r\n# 20 char max\r\noutbound_alt_cid => \r\n\r\n# Y/N only\r\nconf_qualify => Y\r\n\r\n# 255 char max\r\nwebphone_layout => \r\n','2025-06-23 16:43:10'),
    ('QC_STATUS_TEMPLATE','Sample QC Status Template','QC_TEMPLATE','---ALL---','# These types of containers are simply used for creating a list of \r\n# QC-enabled statuses to apply to campaigns, lists, and ingroups.\r\n# Simply put all the statuses that this template should allow in\r\n# a comma-delimited string, as below:\r\n\r\nSALE,DNC,NI','2025-06-23 16:43:10'),
    ('INTERNATIONAL_DNC_IMPORT','Process DNC lists of various countries from FTP site','PERL_CLI','---ALL---','# This setting container is used for the international DNC system. \r\n# The below two settings are mandatory for importing suppression lists\r\n# and tell the import process where to look for new files and where to\r\n# move them when handled.  These settings cannot have the same value. \r\n--file-dir=/root/ftp\r\n--file-destination=/root/ftp/DONE\r\n\r\n# Uncomment below and set the status to whatever custom disposition you \r\n# would like already-loaded leads to be set to when they dedupe against\r\n# a country\'s DNC list (default is \"DNCI\")\r\n# --dnc-status-override=BMNR\r\n\r\n# The below settings are optional for when files are stored on a remote\r\n# server.  It is strongly recommended these settings are not used and\r\n# that the processing scripts and files are stored locally on the same\r\n# server. \r\n# --ftp-host=localhost\r\n# --ftp-user=user\r\n# --ftp-pwd=pwd\r\n# --ftp-port=21\r\n# --ftp-passive=1\r\n','2025-06-23 16:43:10'),
    ('DNC_IMPORT_FORMATS','Import formats for DNC files','OTHER','---ALL---','# This setting container is used for storing file formats used when \r\n# loading DNC suppression lists into the dialer. \r\n#\r\n# import template => (delimited|fixed),delimiter,phone1(,phone2,phone3)\r\n#\r\n# For delimited files, the phone1 value should be the index value of\r\n# the field where the phone appears.  The first array index is 0 and\r\n# indexes continue through the natural numbers.\r\n\r\n# In delimited files, acceptable values for the \"delimiter\" field are:\r\n# - \"tab\", \"pipe\", \"comma\", \"quote-comma\"\r\nBASIC_DELIMITED_FORMAT => delimited,pipe,0\r\n\r\n# If the phone number is split into multiple fields (ex: area code in\r\n# one field, rest of the number in another), simply list additional \r\n# indices of the phone number fields separated by commas in the order \r\n# in which the data should be combined to make the complete phone \r\n# number \r\nDELIMITED_WITH_AC_AND_EXCHANGE_SPLIT => delimited,tab,0,1\r\n\r\n# For fixed-length files, the phone field values should be of the type:\r\n# - \"starting_position|length\"\r\nBASIC_FIXED_FORMAT => fixed,,0|10\r\n\r\n# (delimited|fixed) is not used for CSV/Excel files, so all that needs \r\n# providing for those is the index field value(s) of the phone number\r\nBASIC_CSV_OR_EXCEL_FORMAT => ,,0','2025-06-23 16:43:10'),
    ('DNC_CURRENT_BLOCKED_LISTS','Lists currently blocked due to pending DNC scrub','READ_ONLY','---ALL---','','2025-06-23 16:43:10'),
    ('USER_LOCATIONS_SYSTEM','User Locations List','OTHER','---ALL---',';location|description\n|default\n','2025-06-23 16:43:10'),
    ('USER_CODES_SYSTEM','User Codes List','OTHER','---ALL---','','2025-06-23 16:43:10'),
    ('VICIPHONE_SETTINGS','VICIphone WebRTC Extra Settings','WEBPHONE_SETTINGS','---ALL---','# determines if automatic gain control is enabled\nautoGain : 0\n\n# determines if echo cancellation is enabled\nechoCan : 0\n\n# determines if noise suppression is enabled\nnoiseSup :0\n\n# determines if the reg_exten is called upon successful registration\ndialRegExten : 1\n\n# determines the regional sound to use for progress audio\nprogReg : na\n\n# English translation phrases\nlangAttempting:\"Attempting\"\nlangConnected:\"WS Connected\"\nlangDisconnected:\"WS Disconnected\"\nlangExten:\"Extension\"\nlangIncall:\"Incall\"\nlangInit:\"Initializing...\"\nlangRedirect:\"Redirect\"\nlangRegFailed:\"Reg. Failed\"\nlangRegistering:\"Registering\"\nlangRegistered:\"Registered\"\nlangReject:\"Rejected\"\nlangRinging:\"Ringing\"\nlangSend:\"Send\"\nlangTrying:\"Trying\"\nlangUnregFailed:\"Unreg. Failed\"\nlangUnregistered:\"Unregistered\"\nlangUnregistering:\"Unregistering\"\nlangWebrtcError:\"Something went wrong with WebRTC. Either your bser does not support the necessary WebRTC functions, you did not allow your bser to access the microphone, or there is a configuration issue. Please check your bsers error console for more details. For a list of compatible bsers please vist http://webrtc.org/\"','2025-06-23 16:43:10'),
    ('CONFETTI_SETTINGS','Confetti settings for screen display','OTHER','---ALL---','; Confetti settings, to add visual interest to certain events\r\n; duration is how long the confetti animation runs, maxParticleCount is the\r\n; max number of confetti \"pieces\", and particleSpeed is how fast they float\r\nduration => 2\r\nmaxParticleCount => 2350\r\nparticleSpeed => 2\r\n','2025-06-23 16:43:10'),
    ('HOPPER_CLI_FLAGS','Comand-line flags for hopper process','PERL_CLI','---ALL---','','2025-06-23 16:43:10'),
    ('AGENT_LATENCY_LOGGING','Default agent latency logging settings','PERL_CLI','---ALL---','minimum_gap => 30\r\nemail_sender => \r\nemail_list => \r\nemail_subject => Agent Network Alert','2025-06-23 16:43:10'),
    ('EXAMPLE_LIST_WEEKDAY_RESETS','Example Weekday List Resets Container settings','LIST_WEEKDAY_RESETS','---ALL---','; weekday => reset-times in 24-hour time separated by dashes\r\nmonday => 0830-1230-1800\r\ntuesday => 0900-1400-1830\r\nwednesday => 0930-1200-1730-1900\r\nthursday => 1030-1330-1900\r\nfriday => 0800-1300-1530\r\nsaturday => 0930-1100\r\nsunday => 1000','2025-06-23 16:43:10'),
    ('EXAMPLE_VID_PROMPT_SPECIAL','Example Call Menu VID Special Container settings','CM_VIDPROMPT_SPECIAL','---ALL---','list_ingroup => 102,TEST_IN2\r\nlist_ingroup => 103,TEST_IN3\r\nlist_ingroup => 104,TEST_IN4\r\ndefault_ingroup => TEST_IN5\r\nnot_found_action => new_lead\r\nnew_lead_ingroup => TEST_IN','2025-06-23 16:43:10'),
    ('VERM_STATUS_NAMES_OVERRIDE','Override dialer status names in enhanced reporting','OTHER','---ALL---','; For each status name you want overridden, type the status followed by\r\n; a pipe, then the new status name\r\n; Ex:\r\n; NZ|Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupoka\r\n201214|Request To Cancel\r\n210200|No Answer-Incomplete Call\r\n210201|Contact Established\r\n210202|Provider Review - HB\r\n210203|Promise to Pay\r\n210204|Setup Payment Plan\r\n210205|Research-Inquiry\r\n210206|Voice Mail Left - HB\r\n210207|Do Not Call\r\n210208|Appeal Verification\r\n210209|Bad Phone\r\n210210|Bad Address\r\n210211|Direct Pay Verification\r\n210213|Provider Approved\r\n210215|Update Notes Only\r\n210216|Voicemail-No Status Change\r\n210217|Sent Letter Request - HB\r\n210218|Auto VoiceMail Left - HB\r\n210219|Auto VoiceMail-No Status Change\r\n210302|Provider Review - LB\r\n210306|Voice Mail Left - LB\r\n210317|Sent Letter Request - LB\r\n210318|Auto VoiceMail Left - LB\r\n211503|Provider - COVID-19\r\n211603|Transferred Call to MLA\r\n','2025-06-23 16:43:10'),
    ('VERM_REPORT_OPTIONS','Container for customizing VERM report output','OTHER','---ALL---','; This is the report queue used if none is chosen by the user\r\n; It\'s preloaded in some forms as well\r\nVERM_default_report_queue => ALL\r\n\r\n; If there are statuses to exclude from reports, list them here\r\n; Separate with commas.  Default is AFTHRS\r\nexc_addtl_statuses => AFTHRS\r\n\r\n; Set the below value to 1 (or anything non-blank/non-zero) in order to \r\n; show the agents ID in addition to their full name in the report results\r\nshow_full_agent_info => 1\r\n\r\n; Some reports count \"lost\" calls - which are defined by the below variable\r\n; listing what you define as \"lost\" dispos.  Separate with commas.\r\nlost_statuses => LOST,210208,DISPO\r\n\r\n; You can create a detailed IVR survey report for ingroups by defining\r\n; \"ivr_survey_ingroups_detail\" and \"ivr_survey_ingroups_voicemails.\"\r\n; For \"details\", supply an ingroup used as a tracking group on call menus.\r\n; Then, add a pipe and after that list all call menus that use the ingroup\r\n; as the tracking group, separating each with a comma\r\n; To track whether the calls went to voicemail, list every call menu/option\r\n; combination that goes to voicemail, separating the call menu from the \r\n; option with a pipe.  One callmenu/option combo per line.\r\nivr_survey_ingroups_detail => 521205|561401,561402,561403,561404,561505\r\nivr_survey_ingroups_voicemails => 561505|t\r\n\r\n; #####################################################\r\n; # ALL of the below are used in the wallboard report #\r\n; #####################################################\r\nVERM_default_outb_widget_queue => ALL_OUT\r\nVERM_default_inb_widget_queue1 => 514915v_USA_Shared\r\nVERM_default_inb_widget_queue2 => 515915v_MLA_Shared\r\n\r\n; Used specifically for the SLA widget\r\n; Uses ingroups - separate multiple ingroups by commas\r\n; Comment out or leave blank to count all ingroups\r\nSLA_LEVEL_PCT_ingroups => 514915v,515915v\r\n\r\n; This removes remote agents from the wallboard reports\r\n; Comment out to include remote agents (or set to zero)\r\nomit_remote_agents => 1\r\n\r\n\r\n; #### AUTO DOWNLOAD ####\r\n; If the \"total calls\" value on any report requested exceeds the below \r\n; limit, automatically download the three \"DETAILS\" reports instead\r\n; of attempting to display that many records on-screen\r\nauto_download_limit => 50000\r\n\r\n; #### OUTCOMES report overrides ####\r\n; Use \"outcome_lagged_status_overrides\" for conditions where the call \r\n; record in the vicidial_log or vicidial_closer_log table has no uniqueid\r\n; value despite having a status/outcome, which can indicate a call \r\n; affected by network lag for certain statuses.  This will change the call \r\n; status to \"LAGGED\".  Separate statuses with commas.  Default is the \r\n; automatic \"PU\" status.\r\noutcome_lagged_status_overrides => PU\r\n\r\n; Use \"unknown_network_statuses\" to change call statuses to read \"Network/\r\n; LAGGED\" on the OUTCOMES report. Separate statuses with commas.\r\n; IMPORTANT: if you are using the outcome_lagged_status_overrides option \r\n; above, make sure \"LAGGED\" is one of the unknown_network_statuses here\r\n; unknown_network_statuses => LAGGED\r\n\r\n; Use \"outcome_status_overrides\" to change one status to another on the \r\n; OUTCOMES report.  Overrides are comma-separated pairs of dispositions  \r\n; where the first disposition is the disposition to change, and the second\r\n; is the disposition to change to.  Separate pairs with a pipe character as\r\n; in the below example.  Off by default.\r\n; outcome_status_overrides => CBHOLD,DISPO|XFER,AL','2025-06-23 16:43:10'),
    ('VICIDIAL_TIMEOFF_SETTINGS','Settings for time-off admin utility','OTHER','---ALL---','; Comma-delimited time-off codes - MANDATORY, must have at least one defined. \r\n; Default is \'VAC\' for vacation\r\ntimeoff_types => VAC\r\n\r\n; optional, if set to \'1\' will show all viewable agents, even ones with no \r\n; time off for month.  Default is 0\r\ndisplay_all_agents => 0\r\n\r\n; optional, used to filter users displayed, in addition to user_group \r\n; permissions\r\nuser_filter_SQL =>  \r\n\r\n; optional, uses columns from vicidial_users table.   Defaults to \r\n; full_name asc, user asc if commented out or non-existent\r\n; sort_SQL => full_name asc, user asc\r\n\r\n; include custom coding for misc download coding where \"custom_download\" \r\n; marked in agent_timeoff_script.php - DO NOT USE WITHOUT CODING KNOWLEDGE\r\n; set to \'1\' to activate\r\ncustom_download => 0','2025-06-23 16:43:10'),
    ('FAILED_DIAL_MESSAGE_OVERRIDE','Failed Dial Message Override','OTHER','---ALL---','Unable to complete the call at this time.\nPlease try again later.','2025-06-23 16:43:10');
